//ACCOUNT ACTIONS
export const UPDATE_ACCOUNT_DATA = "UPDATE_ACCOUNT_DATA";

//EDITOR ACTIONS
export const INIT_SHOW_DATA = 'INIT_SHOW_DATA';

//ASSET MODIFY ACTIONS
export const ASSET_SET_MULTIPLE_ATTRIBUTE = 'ASSET_SET_MULTIPLE_ATTRIBUTE';
export const ASSET_SET_STYLE = 'ASSET_SET_STYLE';
export const ASSET_CREATE = "ASSET_CREATE";
export const ASSET_SELECTED = "ASSET_SELECTED";
export const ASSET_COPY = 'ASSET_COPY';
export const ASSET_PASTE = 'ASSET_PASTE';
export const ASSET_SORT = 'ASSET_SORT';
export const ASSET_DELETE = 'ASSET_DELETE';
export const ASSET_SET_ATTRIBUTE = "ASSET_SET_ATTRIBUTE";

// SLIDE ACTIONS
export const SLIDE_CONTEXT_SET_SIZE_UNIT = "SLIDE_CONTEXT_SET_SIZE_UNIT";
export const SLIDE_CONTEXT_SET_POSITION_UNIT = "SLIDE_CONTEXT_SET_POSITION_UNIT";
export const SLIDE_CREATE = 'SLIDE_CREATE';
export const SLIDE_COPY = 'SLIDE_COPY';
export const SLIDE_DELETE = 'SLIDE_DELETE';
export const SLIDE_RENAME = 'SLIDE_RENAME';
export const SLIDE_SELECT = 'SLIDE_SELECT';
export const SLIDE_SET_THUMBNAIL= 'SLIDE_SET_THUMBNAIL';
export const EXCHANGE_SLIDE = 'EXCHANGE_SLIDE';
export const SLIDE_SET_NOTE = 'SLIDE_SET_NOTE';

//DIALOG ACTIONS
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const RELEASE_DIALOG = 'RELEASE_DIALOG';
export const TOGGLE_SLIDE_MANAGER = 'TOGGLE_SLIDE_MANAGER';