const AssetTypes = {
  TYPE_TEXT: 'ASSET_TYPE_TEXT',
  TYPE_IMAGE: 'ASSET_TYPE_IMAGE',
  TYPE_VIDEO: 'ASSET_TYPE_VIDEO',
  TYPE_SHAPE: 'ASSET_TYPE_SHAPE',
  TYPE_TABLE: 'ASSET_TYPE_TABLE',
  TYPE_CUSTOM: 'TYPE_CUSTOM',
  TYPE_PREVIEW: 'TYPE_PREVIEW'
}

export default AssetTypes;
