export const ASSET_CREATE = 'EDITOR.ASSET.ASSET_CREATE';
export const ASSET_SET_ATTRIBUTE = 'EDITOR.ASSET.ASSET_SET_ATTRIBUTE';
export const ASSET_SET_STYLE = 'EDITOR.ASSET.ASSET_SET_STYLE';
export const SELECT_ASSET = 'EDITOR.ASSET.SELECT_ASSET';
export const PASTE_ASSET = 'EDITOR.ASSET.PASTE_ASSET';
export const COPY_ASSET = 'EDITOR.ASSET.COPY_ASSET';
export const SORT_ASSET = 'EDITOR.ASSET.SORT_ASSET';
export const DELETE_ASSET = 'EDITOR.ASSET.DELETE_ASSET';